SEACrowd/seacrowd-datahub

- seacrowd/sea_datasets/mc4_indo/mc4_indo.py
> Closes #61 | Create dataset loader for mc4-indo #61

- seacrowd/sea_datasets/wikiann/wikiann.py
> Closes #1 | Update WikiANN with other South East Asia languages

- seacrowd/utils/constants.py
To cater to this dataloader's needs: #72 (PR) / #24 (Issue).
> Closes #130 | Add new task: SPAN_ABSA

- seacrowd/sea_datasets/shopee_reviews_tagalog/shopee_reviews_tagalog.py
> Closes #108 | Add Shopee Reviews Tagalog dataloader

- .github/workflows/stale.yml
A PR for do a dry-run of this newly revamped workflow
> Testing on #173

- seacrowd/sea_datasets/limesoda/limesoda.py
Please name your PR after the issue it closes. You can use the following line: "Closes #96 " where you replace the ISSUE-NUMBER with the one corresponding to your dataset.
> Closes #96 | Create dataset loader for LimeSoda

- seacrowd/sea_datasets/burmese_romanize/burmese_romanize.py
> Closes #64 | Implement Burmese Name Romanization Dataloader

- REVIEWING.md
This is a followup PR on #156, since the Dataloader Reviewing SOP hasn't been added to base branch when it was merged to `master`
> Add Dataloader Reviewing SOP to REVIEW.md

- requirements.txt
Added opencv-python library for video related tasks.
> Add opencv-python library into requirements.txt

- seacrowd/sea_datasets/uit_vsmec/uit_vsmec.py
Please name your PR after the issue it closes. You can use the following line: "Closes #209 " where you replace the ISSUE-NUMBER with the one corresponding to your dataset.
> Closes #209 | Implement the dataloader for UIT-VSMEC

- seacrowd/sea_datasets/melayu_sarawak/melayu_sarawak.py
> Closes #205 | Implement dataloader for Melayu_Sarawak

- seacrowd/sea_datasets/icon/icon.py
> Closes #161 | Create dataset loader for ICON 161

- .github/workflows/stale.yml
Fixing this [action runs](https://github.com/SEACrowd/seacrowd-datahub/actions/runs/7763751772). Has been tested to work on debug-mode in [this run](https://github.com/SEACrowd/seacrowd-datahub/actions/runs/7765021421) and will check the comments on the next run in `master` branch
> Fix: wrong quote in message

- seacrowd/sea_datasets/dengue_filipino/dengue_filipino.py
> Closes #140 | Add Dengue Filipino

- seacrowd/sea_datasets/id_sent_emo_mobile_apps/id_sent_emo_mobile_apps.py
> Closes #308 | Implement dataloader for Multilabel Multiclass Sentiment and Emotion Dataset from Indonesian Mobile Application Review

- seacrowd/sea_datasets/identifikasi_bahasa/identifikasi_bahasa.py
> Closes #363 | Create dataset loader for identifikasi-bahasa

- seacrowd/sea_datasets/gklmip_newsclass/gklmip_newsclass.py
> Closes #362 | Create dataset loader for GKLMIP Khmer News Dataset

- seacrowd/sea_datasets/thaigov/thaigov.py
> add thaigov

- requirements.txt
- seacrowd/sea_datasets/sarawak_malay/sarawak_malay.py
> Closes #444  | Create dataset loader for Sarawak Malay

- seacrowd/sea_datasets/thai_depression/thai_depression.py
> Closes #145 | Thai Depression

- seacrowd/sea_datasets/lazada_review_filipino/lazada_review_filipino.py
> Closes #104 | Add lazada_review_filipino

- seacrowd/sea_datasets/flores200/flores200.py
Closes [#46](https://github.com/SEACrowd/seacrowd-datahub/issues/46)
> Closes #46 | Create dataloader for Flores200

- requirements.txt
Related: https://github.com/SEACrowd/seacrowd-datahub/pull/460
> add pyreadr==0.5.0

- seacrowd/utils/constants.py
Adding relation extraction task for #222. Per the recommendation in https://github.com/SEACrowd/seacrowd-datahub/pull/469#issuecomment-1997344880, I'm splitting the config changes from the PR for #222 into this PR. The dataloader has been tested and works.
> Add relation extraction task

- seacrowd/sea_datasets/creole_rc/creole_rc.py
- seacrowd/utils/constants.py
> Closes #222 | Create dataset loader for CreoleRC

- seacrowd/sea_datasets/my_paraphrase/my_paraphrase.py
- seacrowd/utils/constants.py
> Closes #341  | Create dataset loader for myParaphrase

- seacrowd/sea_datasets/uit_vicov19qa/uit_vicov19qa.py
> Closes #275 | Create dataset loader for UIT-ViCoV19QA #275

- seacrowd/sea_datasets/tatabahasa/tatabahasa.py
> Closes #530 | Add/Update Dataloader Tatabahasa

- seacrowd/sea_datasets/indowiki/indowiki.py
> Closes #347 | Create dataset loader for IndoWiki

- seacrowd/utils/common_parser.py
> update common_parser for UD JV_CSUI

- seacrowd/sea_datasets/bioner_id/bioner_id.py
> Closes #428 | Create dataset loader for Indonesia BioNER

- seacrowd/sea_datasets/id_newspaper_2018/id_newspaper_2018.py
> Closes #516 | Add/Update Dataloader id_newspaper_2018

- seacrowd/sea_datasets/m3exam/m3exam.py
Fixed problem with empty answer for Thai language. Related #157 and PR [302](https://github.com/SEACrowd/seacrowd-datahub/pull/302)
> Update #157 | Create dataset loader for M3Exam

- seacrowd/sea_datasets/idner_news_2k/idner_news_2k.py
> Closes #534 | Add/Update Dataloader idner_news_2k

- .gitignore
To ignore temporary / local / downloaded dataset
> Add `data/` to .gitignore

- seacrowd/sea_datasets/code_mixed_jv_id/code_mixed_jv_id.py
- seacrowd/sea_datasets/indolem_ud_id_gsd/indolem_ud_id_gsd.py
- seacrowd/sea_datasets/malaysia_ai_hansard/malaysia_ai_hansard.py
- seacrowd/sea_datasets/malindo_parallel/malindo_parallel.py
- seacrowd/sea_datasets/nllb_seed/nllb_seed.py
- seacrowd/sea_datasets/nusatranslation_senti/nusatranslation_senti.py
- seacrowd/sea_datasets/parallel_id_nyo/parallel_id_nyo.py
- seacrowd/sea_datasets/postag_su/postag_su.py
- seacrowd/sea_datasets/ted_en_id/ted_en_id.py
- seacrowd/sea_datasets/toxicity_200/toxicity_200.py
- seacrowd/sea_datasets/ud_id_csui/ud_id_csui.py
Changelog:
Removing invocation of `datasets.load_dataset` from main endpoint of the module (`__name__ == '__main__'`)
> remove main entry of module for dataloaders

- seacrowd/sea_datasets/asr_ibsc/asr_ibsc.py
> Closes #440 | Add Dataloader ASR-IBSC: AN IBAN SPEECH CORPORA

- seacrowd/sea_datasets/senti_bahasa_rojak/senti_bahasa_rojak.py
Closes [#497](https://github.com/SEACrowd/seacrowd-datahub/issues/497)
> [New Feature] Add SentiBahasaRojak Dataset
