SEACrowd/seacrowd-datahub

seacrowd/sea_datasets/filipino_slang_norm/filipino_slang_norm.py

Closes #15 | Add filipino_slang_norm data loader

---

seacrowd/sea_datasets/tlunified_ner/tlunified_ner.py

Closes #11 | Add tlunified_ner data loader

---

conda.yml
requirements.txt

Reason:
I was trying to follow the steps on creating the venv for this repo (using ```conda version: 23.5.2```) however I encountered some issues when executing conda env create -f conda.yml. It's caused by several requirements conflicting each other for the following points
1. ```pandas==1.3.3``` throws an error on ```subprocess``` with following message:
```Pip subprocess error:
error: subprocess-exited-with-error
× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> [17 lines of output]
....
File "<string>", line 18, in <module>
ModuleNotFoundError: No module named 'numpy'
[end of output]
note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
× Getting requirements to build wheel did not run …
```

Add proposed change to venv files in SEACrowd Initialization

---

templates/template.py

Closes #42 
Fix confusing TO-DO in templates/templates.py, regarding possible values for ```seacrowd_schema_name```
cc @holylovenia

Closes #42 | Fix guide related to seacrowd_schema_name in templates

---

seacrowd/sea_datasets/tatoeba/tatoeba.py

Closes #5
Some notable things to point out from this dataset:
- Instead of implementing one loader per language, I created several configs per language in a single loader. TThis means that the configs would look like this: `tatoeba.ind_seacrowd_t2t`, `tatoeba.ind_source` and so on. When testing, we should pass a value to the `--subset_id` parameter like so:
```
python -m tests.test_seacrowd seacrwod/sea_datasets/tatoeba/tatoeba.py --subset_id tatoeba.ind
```
- The [`source_lang` field in the original HF link](https://huggingface.co/datasets/xtreme/viewer/tatoeba.tgl) seems incorrect?  I'm not familiar with this dataset so for my implementation I just copied over what's in the source. Let me know if I should "override" this with the actual language code.

Closes #5 | Add tatoeba dataset loader

---

seacrowd/sea_datasets/belebele/belebele.py

Three things have changed:
1. Add default config of `belebele_source` and `belebele_seacrowd_qa`
2. Reduces the number of possible `belebele` sources to match its intention to load SEA langs only (previously, all langs are being dumped) -- check the original ticket to ensure that the values are matched with this new changes
3. Fixing `subset_id` values from `belebele` to specified ISO 639-3 lang codes
4. Adjust the data source path in `_split_generators` based on the proposed fix in (1) and (2)
Note: This passed the test cases, unlike prev implementation, feel free to test it on 2 different versions (prev one that has been merged to `master` and this branch version)

Closes #73 | Fix Belebele Dataloader

---

seacrowd/sea_datasets/cebuaner/cebuaner.py

Closes #23 | Add CebuaNER data loader

---

seacrowd/sea_datasets/culturax/culturax.py

Closes #84 
I implemented one config per language/subset. Thus, configs will look like this: `culturax_id_source`, `culturax_jv_seacrowd_ssp`, etc. When testing, pass `culturax_<subset>` to the `--subset_id` parameter.

Closes #84 | Implement CulturaX Dataloader

---

seacrowd/sea_datasets/yunshan_cup_2020/yunshan_cup_2020.py

Please name your PR after the issue it closes. You can use the following line: "Closes #79" where you replace the ISSUE-NUMBER with the one corresponding to your dataset.

Closes #79 | Add dataloader for Yunshan-Cup-2020 Lao POS

---

seacrowd/sea_datasets/xm3600/xm3600.py

Closes #76 | Create dataset loader for XM3600

---

seacrowd/sea_datasets/fakenews_ph/fakenews_ph.py

Closes #107 | Implement FakeNewsPH dataloader

---

seacrowd/sea_datasets/mabl/mabl.py

Closes #70
Notes
- Although multilingual, `mabl_source` and `mabl_seacrowd` are implemented. In this case, it loads all languages. 
- Might need another set of eyes to check the items in my seacrowd schema. I included the `startphrase` in both the `question` and `context`. Not sure if I should just leave one blank.
```
python -m tests.test_seacrowd seacrowd/sea_datasets/mabl/mabl.py  # Loads all data for all languages
python -m tests.test_seacrowd seacrowd/sea_datasets/mabl/mabl.py --subset_id mabl_jav  # Loads jav subset others: [ind, sun]
```

Closes #70 | Add MABL dataloader

---

seacrowd/sea_datasets/phost/phost.py

Closes #33 | Create dataset loader for PhoST

---

seacrowd/sea_datasets/cub_bahasa/cub_bahasa.py

Closes #68 | Implement CUB Bahasa Dataloader

---

seacrowd/sea_datasets/khmer_alt_pos/khmer_alt_pos.py

Closes #93 | Add dataloader for Khmer ALT POS

---

seacrowd/sea_datasets/udhr/udhr.py

Closes #82 | Create dataset loader for UDHR

---

seacrowd/sea_datasets/xquad/xquad.py

Closes #3 
Because this dataset is multilingual, there are 3 subsets: ["xquad", "xquad.vi", "xquad.th"]. The `xquad` subset, which combines all the languages, is needed because the test requires it. Without it, I ran into this problem running the test:
```
> python -m tests.test_seacrowd seacrowd/sea_datasets/xquad/xquad.py
INFO:__main__:args: Namespace(path='seacrowd/sea_datasets/xquad/xquad.py', schema=None, subset_id=None, data_dir=None, use_auth_token=None)
INFO:__main__:self.PATH: seacrowd/sea_datasets/xquad/xquad.py
INFO:__main__:self.SUBSET_ID: xquad
INFO:__main__:self.SCHEMA: None
INFO:__main__:self.DATA_DIR: None
INFO:__main__:Checking for _SUPPORTED_TASKS ...
module seacrowd.sea_datasets.xquad.xquad
INFO:__main__:Found _SUPPORTED_TASKS=[<Tasks.QUESTION_ANSWERING: 'QA'>] …
```

Closes #3  | Create dataset loader for XQuAD

---

seacrowd/sea_datasets/copal/copal.py

Closes [#36](https://github.com/SEACrowd/seacrowd-datahub/issues/36)

Closes #36 | Add COPAL dataloader

---

seacrowd/sea_datasets/glotstorybook/glotstorybook.py

Closes #91 | Implement GlotStoryBook Dataloader

---

.github/workflows/stale.yml

Hi @holylovenia and @SamuelCahyawijaya, regarding the mistag GH Actions on marking the staled issue, I found the issue lies in a current workflow that wrongly tags open Issues with a PR attached to it (the mistag issue happens in #24).
The issues are caused due to 2 unexpected behavior:
1. the field of `updated_at` from Github Issue that isn't being updated if a PR closing that issue is being linked
2. The `update_at` field is used by GH Stale Workflow to mark no activity issue.
Hence, marking an issue with a flag of either `pr-ready` or `in progress` is essential to exempt those issues from being checked and marked as Stale Issues.
In addition, I'm proposing to increase the number of operations per run (based on the est. upper bound of open issues that we have right now, 100) so all …

Update stale workflow to avoid Misflag Issue

---

seacrowd/sea_datasets/filipino_hatespeech_tiktok/filipino_hatespeech_tiktok.py

Closes #65 | Create dataset loader for filipino-hatespeech-text

---

requirements.txt
seacrowd/sea_datasets/filipino_words_aoa/filipino_words_aoa.py

Closes #94 .
- Decided not to include the `seq_label` task for the POS tags in the dataset because (a) they don't follow the schema, and (b) in my opinion, it isn't "true" POS-tagging. As a native Filipino speaker, there are some words in the dataset that can vary in POS based on how they're used.
- `dl_manager` isn't used in `_split_generators`. I used `urllib.request.urlretrieve()` and the `openpyxl` package instead.

Closes #94 | Create dataset loader for Filipino Age-of-Acquisition Words

---

requirements.txt

Relevant for reading parquet files.
Implicit dependency for pandas when executing pd.read_parquet(..., engine="pyarrow")
Related #242

Add pyarrow to dependencies

---

seacrowd/sea_datasets/belebele/belebele.py
seacrowd/sea_datasets/coco_35l/coco_35l.py

Closes #78 | Create dataset loader for COCO-35L

---

seacrowd/sea_datasets/newsph/newsph.py

Closes #106 | Create dataset loader for NewsPH

---

seacrowd/sea_datasets/palito/palito.py

Closes #30 | Add palito dataset

---

seacrowd/sea_datasets/cc_aligned_sent/cc_aligned_sent.py

Closes #160 | Add data loader for CC-Aligned Sentence Pairs

---

seacrowd/sea_datasets/fsl_105/fsl_105.py

Closes #13 | Create dataset loader for FSL-105

---

seacrowd/sea_datasets/bloom_speech/bloom_speech.py

Closes #163 | Add Bloom-Speech Dataloader

---

seacrowd/sea_datasets/openlid/openlid.py

Closes #144 | Add OpenLID Dataloader

---

seacrowd/sea_datasets/memolon/memolon.py

Closes #37 
> Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
For this dataset, only source schema will be implemented (see #37)
> Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py`.
Fails not having `<dataset_name>_source` in config. This dataset have multiple languages/subsets and config is named as `<dataset_name>_<lang>_source`.

Closes #37 | Create dataset loader for MEmoLon

---

seacrowd/sea_datasets/vistec_tp_th_21/vistec_tp_th_21.py

Closes #201 .
Note that this dataset has a specific label for NER. It only contains True/False labels for NER.

Closes #201 | Implemente dataloader for VISTEC_TP_TH_21

---

seacrowd/sea_datasets/melayu_standard_lisan/melayu_standard_lisan.py

Closes #203 | Implement dataloader for Melayu_Standard_Lisan

---

seacrowd/sea_datasets/tcope/tcope.py

Closes #50.
- Decided not to implement schema for dependency parsing task. Corpus has dependency-parsed text but no information on grammatical relationships between words. Essentially it's similar to just sequence labeling. Let me know if we can still implement this task in another way though.

Closes #50 | Create dataset loader for TCOPE

---

seacrowd/sea_datasets/bloom_vist/bloom_vist.py

Closes #158 | Add Dataloader Bloom-VIST

---

seacrowd/sea_datasets/sap_wat/sap_wat.py

Please name your PR after the issue it closes. You can use the following line: "Closes #103" where you replace the ISSUE-NUMBER with the one corresponding to your dataset.

Closes #103 | Create dataset loader for SAP WAT

---

seacrowd/sea_datasets/thai_sum/thai_sum.py

Please name your PR after the issue it closes. You can use the following line: "Closes #181" where you replace the #181 with the one corresponding to your dataset.

Closes #181 | Create the dataloader for thai_sum

---

seacrowd/sea_datasets/melayu_brunei/melayu_brunei.py

Closes #207. 
I want to report that after checking the raw data from the source, I found that the dataset only consists of Brunei. There is no Melayu language included in the dataset.

Closes #207 | implemente the dataloader for Melayu_Brunei

---

seacrowd/sea_datasets/uit_vsfc/uit_vsfc.py

Closes #208. 
Note that since this dataset supports both topic modeling and sentiment analysis, they both fall into the schema of General Text Classification. During unit testing, please run the command:
`
python -m tests.test_seacrowd seacrowd/sea_datasets/uit_vsfc/uit_vsfc.py --subset_id uit_vsfc_sentiment
`
for sentiment analysis and:
`
python -m tests.test_seacrowd seacrowd/sea_datasets/uit_vsfc/uit_vsfc.py --subset_id uit_vsfc_topic
`
for topic modeling.

Closes #208 | Implement dataloaders for UIT_VSFC

---

seacrowd/sea_datasets/thai_constitution/thai_constitution.py

Closes #111  | Add Thai Constitution

---

seacrowd/sea_datasets/tgl_profanity/tgl_profanity.py

Closes #220 | Add Tagalog Profanity Dataloader

---

seacrowd/sea_datasets/cc100/cc100.py

Closes #148
Because this dataset is multilingual, I added the `cc100_source/seacrowd_ssp` subset, which combines all the languages. This is needed because the test requires it. Without it, I ran into this problem running the test:

Closes #148 | Create dataset loader for CC-100

---

seacrowd/sea_datasets/bloom_captioning/bloom_captioning.py

Closes #162 | Add Bloom-Captioning Dataloader

---

seacrowd/sea_datasets/uit_victsd/uit_victsd.py

Closes #271 | Implement dataloader for UiT-ViCTSD

---

seacrowd/sea_datasets/unimorph/unimorph.py

Resolves #142
Source implementation in HF: https://huggingface.co/datasets/universal_morphologies
The source schema is a bit different as each entry is a lemma. For SEACrowd each entry is a lemma-inflection pair, so the number of documents / examples is higher.

Closes #142 | Add Unimorph v4 dataloader

---

seacrowd/sea_datasets/ara_close/ara_close.py

Closes #14 
Note:
1. In the data card, there are three languages: bcl, tgl, ceb. However, data source for [tgl was deleted](https://github.com/SEACrowd/seacrowd-datahub/issues/14#issuecomment-1869864418).
2. READABILITY_ASSESSMENT [was added to Tasks constants](https://github.com/SEACrowd/seacrowd-datahub/issues/14#issuecomment-1869240572).

Closes #14 | Create dataset loader for ara-close-lange

---

seacrowd/sea_datasets/uit_vion/uit_vion.py

Closes #273 | Implement dataloader for UIT_ViON

---

seacrowd/sea_datasets/spamid_pair/__init__.py
seacrowd/sea_datasets/spamid_pair/spamid_pair.py

Closes #277 | Implement dataloader for spamid_pair

---

seacrowd/utils/constants.py
seacrowd/utils/schemas/__init__.py
seacrowd/utils/schemas/imqa.py

Relate issue #157 and PR [302](https://github.com/SEACrowd/seacrowd-datahub/pull/302)
- Created imqa schema for visual question answering;
- Add VISUAL_QUESTION_ANSWERING task
Schema features:
features = datasets.Features(
{
"id": datasets.Value("string"),
"question_id": datasets.Value("string"),
"document_id": datasets.Value("string"),
"questions": datasets.Sequence(datasets.Value("string")),
"type": datasets.Value("string"),
"choices": datasets.Sequence(datasets.Value("string")),
"context": datasets.Value("string"),
"answer": datasets.Sequence(datasets.Value("string")),
"image_paths": datasets.Sequence(datasets.Value("string")),
"meta": {}
}
)

Related #157 | Add imqa schema and VISUAL_QUESTION_ANSWERING task

---

seacrowd/sea_datasets/mozilla_pontoon/mozilla_pontoon.py

Closes #216 |  Create dataset loader for Mozilla Pontoon

---

seacrowd/sea_datasets/melayu_sabah/melayu_sabah.py

Closes #204.
Note: No paper with related to this dataset.

Closes #204 | Implement dataloader for Melayu_Sabah

---

.github/workflows/stale.yml

Hi @holylovenia @SamuelCahyawijaya, I'm proposing an improvement in Workflow where you can mention the assignee in Staled Issue. I happened to see [this PR in Stale Actions Repo](https://github.com/microsoft/pylance-release/pull/4054/files) and trying to implement it in our reminder message from GH actions.
PS.: the expected output (comments on actual actions) can't be seen on `debug-mode`; that's why I'm trying to merge this to test the actual message, whether it's adhering to the expectations. Feel free to reject this if you have any concerns on this. Thanks

Improvement: Workflow Message to Mention Assignee in Staled Issues

---

seacrowd/utils/common_parser.py

This PR relates to https://github.com/SEACrowd/seacrowd-datahub/pull/247#discussion_r1440043322
and is linked to #247
As discussed in https://github.com/SEACrowd/seacrowd-datahub/pull/328, separating loader efforts from common utility efforts.

ishan/utf-shared-alone Update common_parser.py

---

.github/workflows/stale.yml

After re-reading, actually the previously implemented workflow uses another custom workflow imported to make `assignees` and `author` uname construction works.
which returns unexpected commenting behavior in the new stale
Hence, from the subsequent comment in the SS, I found [this](https://github.com/microsoft/pylance-release/pull/4054#discussion_r1131864892) reference of author and assignees using github internal variable (which is supposedly works since it works in the Issue & PR level and coming from github internal vars)

Fix: Workflow Assignee Mention

---

seacrowd/sea_datasets/ph_fake_news_corpus/ph_fake_news_corpus.py

Closes #17 | Implement dataloader for Philippine Fake News Corpus

---

seacrowd/sea_datasets/lr_sum/lr_sum.py

Closes #359 | Implement dataloader for LR-Sum

---

seacrowd/sea_datasets/openslr/openslr.py

Closes #164 
Note: For subsets SLR35 and SLR36 checked on 2 out of 16 files, because they are very big (each file 1.1-1.4 GB).

Closes #164 | Create dataset loader for OpenSLR

---

seacrowd/sea_datasets/myxnli/myxnli.py

Closes #265 | Implement dataloader for `myxnli`

---

seacrowd/sea_datasets/wisesight_thai_sentiment/wisesight_thai_sentiment.py

Closes #112 | Implement Dataloader for Wisesight Thai Corpus

---

seacrowd/sea_datasets/alt_burmese_treebank/alt_burmese_treebank.py
seacrowd/sea_datasets/alt_burmese_treebank/utils/alt_burmese_treebank_utils.py

Closes #16 
Note:
PR [295](https://github.com/SEACrowd/seacrowd-datahub/pull/295) is related to this PR and issue it closes

Closes #16 | Create dataset loader for ALT Burmese Treebank

---

seacrowd/sea_datasets/audio_keyword_spotting/audio_keyword_spotting.py

Closese #166 | Add Dataloader for Audio Keyword Spotting

---

seacrowd/sea_datasets/filipino_gay_lang/filipino_gay_lang.py

Closes #66.
**Note**: there are 3 separate Excel files for this dataset. I was not sure whether each correspond to train/test/validation, so I combined everything as train.
Makefile output (author name contains special character):
Test run output:

Closes #66 | Create dataset loader for Filipino Gay Language (Swardspeak) #66 

---

seacrowd/sea_datasets/cc_aligned_doc/cc_aligned_doc.py

Closes #159 
Note: Some subset sizes are large, so the test was only conducted on several subsets.

Closes #159 | Create dataset loader for CC-Aligned

---

seacrowd/sea_datasets/thai_toxicity_tweet/thai_toxicity_tweet.py
seacrowd/sea_datasets/thai_toxicity_tweets/thai_toxicity_tweets.py

Closes #268.
Had to close my previous PR due to a mistake while pushing changes, sorry!

Closes #268 | Implement dataloader for Thai Toxicity Tweet Corpus

---

seacrowd/sea_datasets/vlsp2016_ner/vlsp2016_ner.py

Closes #345 | Implemented dataloader for vlsp2016_ner

---

seacrowd/sea_datasets/prdect_id/prdect_id.py

Closes #276
Might need some help in the tests. I can make the `source` schema pass, but not the `seacrowd` ones. I think what's peculiar in this dataset is that it has two types of labels for the same `TEXT` schema. I can make the data loader work by running the following code:
```python
from datasets import load_dataset
sentiment_dset = load_dataset("seacrowd/sea_datasets/prdect_id/prdect_id.py", name="prdect_id_sentiment_seacrowd_text")
emotion_dset =  load_dataset("seacrowd/sea_datasets/prdect_id/prdect_id.py", name="prdect_id_emotion_seacrowd_text")
```

Closes #276 | Implement PRDECT-ID dataloader

---

seacrowd/sea_datasets/bhinneka_korpus/bhinneka_korpus.py

Closes #9 | Add bhinneka_korpus dataset loader

---

seacrowd/sea_datasets/indoner_tourism/indoner_tourism.py

Closes #348 | Implemented dataloader for indoner_tourism

---

seacrowd/sea_datasets/tha_lao_embassy_parcor/tha_lao_embassy_parcor.py

Closes #361 | Create dataset loader for Thai-Lao Parallel Corpus

---

seacrowd/sea_datasets/indoler/indoler.py

Closes #351 
Note:
Despite only having 993 data instances, there are almost 5.9M tokens that need to be processed.
the testcase ran successfully, but took my laptop 150s. test case
If anyone knows how I can optimize this, please do tell me.

Closes #351 | Implemented dataloader for indoler

---

seacrowd/sea_datasets/uit_viocd/uit_viocd.py

Closes #305 | Implement dataloader for UIT_ViOCD

---

seacrowd/sea_datasets/gklmip_sentiment/gklmip_sentiment.py

Closes #358 | Create dataset loader for GKLMIP Product Sentiment

---

seacrowd/sea_datasets/vihealthqa/vihealthqa.py

Close #306 | Create dataset loader for ViHealthQA

---

seacrowd/sea_datasets/beaye_lexicon/beaye_lexicon.py

Closes #10 | Create beaye_lexicon dataset loader

---

seacrowd/sea_datasets/filwordnet/filwordnet.py

Closes #353 
> Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
This dataset is a lexicon. It does not support any tasks. This case is similar to https://github.com/SEACrowd/seacrowd-datahub/pull/155 and https://github.com/SEACrowd/seacrowd-datahub/pull/332
To run tests:
```
python -m tests.test_seacrowd_source_only seacrowd/sea_datasets/filwordnet/filwordnet.py
```

Closes #353| Create dataset loader for FilWordNet

---

seacrowd/sea_datasets/ind_proner/ind_proner.py

Closes [#350](https://github.com/SEACrowd/seacrowd-datahub/issues/350).
The dataloader script does not pass the test suite because this uses a modified naming convention for loading subsets: `ind_proner_automatic_source`, `ind_proner_manual_source`, `ind_proner_automatic_l1_seacrowd_seq_label`, `ind_proner_manual_l1_seacrowd_seq_label`, `ind_proner_automatic_l2_seacrowd_seq_label`, `ind_proner_manual_l2_seacrowd_seq_label`. This was previously discussed in the [#350 issue ticket](https://github.com/SEACrowd/seacrowd-datahub/issues/350).

Closes #350 | Implement dataloader for Indonesian PRONER

---

seacrowd/sea_datasets/tmad_malay_corpus/tmad_malay_corpus.py

Closes #395 | Implement dataloader for IMAD Malay Corpus

---

seacrowd/sea_datasets/mysentence/mysentence.py

Closes #264 | Create dataset loader for mySentence #264

---

REVIEWING.md
templates/template.py

Issue: Reviewer Dataloader SOP instructions and template.py instructions are inconsistent regarding the dataloader class name convention.
With the current instruction at `template.py` it's not clear whether to put "Dataset" as suffix or not while the Dataloader SOP instructions makes it clear that the dataloader class name should include "Dataset" as suffix.
To minimize confusion for both reviewers and dataloader creators, we can do either:
- (a) Update the instruction at [template.py](https://github.com/SEACrowd/seacrowd-datahub/blob/master/templates/template.py)
- (b) Update the instruction at [Dataloader Review SOP](https://github.com/SEACrowd/seacrowd-datahub/blob/master/REVIEWING.md#dataloader-reviewer-sop), item 5.i
This PR implements solution (a). If solution (b) is preferred, …

Update template.py instruction for dataloader class name

---

seacrowd/sea_datasets/qasina/qasina.py

Closes #349 | Create dataset loader for QASiNa

---

seacrowd/sea_datasets/vivos/vivos.py

Closes [#263](https://github.com/SEACrowd/seacrowd-datahub/issues/263).

Closes #263 | Implement dataloader for VIVOS

---

seacrowd/sea_datasets/indonesiannmt/indonesiannmt.py
templates/template.py

Closes #338 | Created DataLoader for IndonesianNMT

---

seacrowd/sea_datasets/kheng_info/kheng_info.py

Closes #366 | Implement dataloader for Kheng.info Speech

---

seacrowd/sea_datasets/vi_pubmed/vi_pubmed.py

Closes [#226](https://github.com/SEACrowd/seacrowd-datahub/issues/226)

Closes #226 | Vi Pubmed dataloader

---

seacrowd/sea_datasets/gatitos/gatitos.py

Closes #147 | implemented dataloader for gatitos dataset

---

seacrowd/sea_datasets/emotes_3k/emotes_3k.py

Closes #340 | Implement Dataloader for emotes_3k

---

seacrowd/sea_datasets/indoqa/indoqa.py

Closes #430
---
**_P.S.:_**
- Dataset is hosted on Google Drive and I experienced some quota issues. Currently in touch with the author.
- Tested with successful cache. If you experienced same problem, you might want to try replacing the cache manually.

Closes #430 | Create dataset loader for IndoQA

---

seacrowd/sea_datasets/xl_jailbreak/xl_jailbreak.py

Closes [#92](https://github.com/SEACrowd/seacrowd-datahub/issues/92)

Closes #92 | Create Jail break data loader

---

seacrowd/sea_datasets/wit/wit.py

Closes [#202 ](https://github.com/SEACrowd/seacrowd-datahub/issues/202).

Closes #202 | Implement dataloader for WIT

---

seacrowd/sea_datasets/ucla_phonetic/ucla_phonetic.py

Closes #394 | Implement dataloader for UCLA Phonetic Corpus

---

seacrowd/sea_datasets/malindo_morph/malindo_morph.py

Closes #193
> Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
This dataset is a lexicon. It does not support any tasks. This case is similar to https://github.com/SEACrowd/seacrowd-datahub/pull/155
To run tests:
```
python -m tests.test_seacrowd_source_only seacrowd/sea_datasets/malindo_morph/malindo_morph.py
```

Closes #193 | Create dataset loader for MALINDO Morph

---

seacrowd/sea_datasets/khpos/khpos.py

Closes #360 | Implement dataloader for khpos

---

seacrowd/sea_datasets/beaye_lexicon/beaye_lexicon.py
seacrowd/sea_datasets/indo_story_cloze/indo_story_cloze.py
seacrowd/sea_datasets/pho_ner_covid/pho_ner_covid.py

Closes [#116](https://github.com/SEACrowd/seacrowd-datahub/issues/116)

Closes #116 | Add pho_ner_covid Dataloader

---

seacrowd/sea_datasets/fsl_105/fsl_105.py
seacrowd/sea_datasets/id_msvd/id_msvd.py
seacrowd/utils/schemas/video.py

As discussed [here](https://github.com/SEACrowd/seacrowd-datahub/pull/135#discussion_r1490931571), for clarity purposes, I suggest changing the `texts` key to `text` so it will indicate a literal text (not a list of texts). Thus, I also changed the keys in relevant dataloaders (#135 & #185). Both dataloaders are already tested and all are OK.

Video schema key change: `texts` to `text`

---

seacrowd/sea_datasets/wili_2018/wili_2018.py

Closes #217 | Implement dataloader for `wili_2018`

---

seacrowd/sea_datasets/myanmar_rakhine_parallel/myanmar_rakhine_parallel.py

Closes #262 | Create dataset loader for Myanmar-Rakhine Parallel

---

seacrowd/sea_datasets/seaeval/seaeval.py

Closes #342 | Implement dataloader for SeaEval

---

seacrowd/sea_datasets/asr_stidusc/asr_stidusc.py

Closes #443 | Add dataloader for ASR-STIDUSC

---

seacrowd/sea_datasets/xl_sum/xl_sum.py

Closes #32 (High Prio) | Extend XL Sum Dataloaders to SEA Langs

---

seacrowd/sea_datasets/asr_sindodusc/asr_sindodusc.py

Closes #439 | Add dataloader for ASR-Sindodusc

---

seacrowd/sea_datasets/indonglish/indonglish.py

Closes #475 | Add dataloader for indonglish-dataset

---

seacrowd/sea_datasets/indonesian_news_dataset/indonesian_news_dataset.py

Closes #422 | Create indonesian_news_dataset dataloader

---

seacrowd/sea_datasets/uit_vihsd/uit_vihsd.py

Closes #309 | Add/Update Dataloader {UIT-ViHSD}
**First line PR Message**: Closes #{ISSUE_NUMBER}
where you replace the {ISSUE_NUMBER} with the one corresponding to your dataset.

Closes #309 | Create dataset loader for Vietnamese Hate Speech Detection (UIT-ViHSD) #309Uit vihsd

---

seacrowd/sea_datasets/asr_smaldusc/asr_smaldusc.py

Closes #441 | Add dataloader for ASR-SMALDUSC

---

seacrowd/sea_datasets/visobert/visobert.py
seacrowd/utils/constants.py

Closes #307 | Implement dataloader for ViSoBERT 

---

seacrowd/sea_datasets/id_sentiment_analysis/id_sentiment_analysis.py
seacrowd/sea_datasets/indo_story_cloze/indo_story_cloze.py

Closes [#51](https://github.com/SEACrowd/seacrowd-datahub/issues/51)

Closes #51 | Add id_sentiment_analysis dataloader

---

seacrowd/sea_datasets/phomt/phomt.py

**Title**: Closes #{ISSUE_NUMBER} | Add/Update Dataloader {DATALOADER_NAME}
**First line PR Message**: Closes #{ISSUE_NUMBER}
where you replace the {ISSUE_NUMBER} with the one corresponding to your dataset.

Closes #115 | Create dataset loader for PhoMT dataset

---

seacrowd/sea_datasets/vispamreviews/vispamreviews.py

 Closes #310 |Create dataset loader for ViSpamReviews #310

---

seacrowd/sea_datasets/struct_amb_ind/struct_amb_ind.py

Closes #267  | Add dataloader for struct_amb_ind

---

seacrowd/sea_datasets/ud_jv_csui/ud_jv_csui.py
seacrowd/utils/common_parser.py

Closes #427 | Create dataset loader for UD Javanese-CSUI

---

seacrowd/sea_datasets/voxlingua/voxlingua.py

**Title**: Closes #446 | Add/Update Dataloader voxlingua
**First line PR Message**: Closes #446 
For 6 & 7, I have tested it using `ceb` language only since the data folder is quite large (up to 6GB per each language)

Closes #446 | Add/Update Dataloader voxlingua

---

seacrowd/sea_datasets/vlsp2016_sa/vlsp2016_sa.py

Closes #344 | Create dataset loader for VLSP2016-SA

---

seacrowd/sea_datasets/malindo_parallel/malindo_parallel.py

Closes #192 | Create dataset loader for MALINDO_parallel

---

seacrowd/sea_datasets/vndt/utils.py
seacrowd/sea_datasets/vndt/vndt.py

Closes #114 | Implement dataloader for VnDT

---

seacrowd/sea_datasets/tydiqa/tydiqa.py

Update subset composition of TydiQA | Close #465 
Decompose the tasks into SelectP, MinSpan, GoldP tasks.
Scripts Passed:
1. ```python -m tests.test_seacrowd seacrowd/sea_datasets/tydiqa/tydiqa.py --subset tydiqa_selectp_thai```
2. ```python -m tests.test_seacrowd seacrowd/sea_datasets/tydiqa/tydiqa.py --subset tydiqa_selectp_indonesian```
3. ```python -m tests.test_seacrowd seacrowd/sea_datasets/tydiqa/tydiqa.py --subset tydiqa_selectp```
4. ```python -m tests.test_seacrowd seacrowd/sea_datasets/tydiqa/tydiqa.py --subset tydiqa_id```
5. ```python -m tests.test_seacrowd seacrowd/sea_datasets/tydiqa/tydiqa.py --subset tydiqa_minspan```
6. ```python -m tests.test_seacrowd seacrowd/sea_datasets/tydiqa/tydiqa.py --subset tydiqa_minspan_thai```
7. ```python -m tests.test_seacrowd …
```

PR for update subset composition of TydiQA | Close #465

---

seacrowd/sea_datasets/balita_nlp/balita_nlp.py

Closes #12
There are many articles in the dataset whose corresponding image file does not exist in the repository. Reporting the statistics here:
- `train` split (281403 total examples): 18923 missing images (~6.72%)
- `test` split (35177 total examples): 2356 missing images (~6.70%)
- `validation` split (35175 total examples): 2369 missing images (~6.73%)

Closes #12 | Add/Update Dataloader BalitaNLP

---

seacrowd/sea_datasets/cosem/cosem.py

Closes [#52](https://github.com/SEACrowd/seacrowd-datahub/issues/52)

Closes #52 | Add cosem dataloader

---

seacrowd/sea_datasets/bactrian_x/bactrian_x.py

Closes #424
I implemented one config per language/subset. Thus, configs will look like this: `bactrian_x_id_source`, `bactrian_x_km_seacrowd_t2t`, etc. When testing, pass `bactrian_x_<subset>` to the `--subset_id` parameter.
As there is one more variable for the input response in the source schema, I added that manually as `Instruction: {instruction}\nInput: {input}"` in `text_1` of `seacrowd_t2t` schema. I don't know if that is allowed, so let's discuss.
Note that for Khmer subset, the loaded data will look as follows:
```
INFO:__main__:Dataset sample [source]
{'instruction': 'តើ\u200bស៊ុម\u200bក្រិត\u200bក្នុង\u200bការ\u200bថត\u200bរូប\u200bតារាសាស្ត្រ\u200bមាន\u200bអ្វីខ្លះ?', 'input': '', 'id': 'dolly-10828', 'output': 'ស៊ុម\u200bក្រិត\u200bក្នុង\u200bការ\u200bថត\u200bរូប\u200bតារាសាស្ …
```

Closes #424 | Add Dataloader Bactrian-X

---

seacrowd/sea_datasets/gnome/gnome.py

Closes #513
Based on discussion [#456](https://github.com/SEACrowd/seacrowd-datahub/pull/456#issuecomment-1978320893), I implemented all possible language pairs listed on the datasheet.
> For parallel MT dataloaders, we agreed upon having a subset for every possible direction with at least 1 SEA language.
Thus, configs will look like this: `gnome_en-id_source`, `gnome_tl-vi_seacrowd_t2t`, etc. When testing, pass `gnome_<subset>` to the `--subset_id` parameter.
<details close>
<summary>Here is a useful script to test all possible language pairs:</summary>
To run this script, save it to a file (e.g., `gnome_tests.sh`), make it executable with `chmod +x gnome_tests.sh`, and execute it with `./gnome_tests.sh`. Ensure you run the script from the seacrowd root directory.
```bash
#!/bin/bash …
```

Closes #513 | Add Dataloader GNOME

---

templates/template.py

**Issue**: This PR simply adds the schemas import statement in `templates/template.py` (`from seacrowd.utils import schemas`). This is to ease the `_info(self)` section for the seacrowd schema.
After working on the data loader multiple times, I had to manually (or automatically) import to fill in that code section. By importing schemas beforehand, it at least eases (a bit) the repetitive issue.

Import `schemas` beforehand on `templates/template.py`

---

tests/test_seacrowd.py

**Issue**:
This is also a (**really**) minor thing that I noticed when running tests with the `--schema` parameter.
I noticed that all the items in the `VALID_SCHEMAS` variable are strings in full capital letters, there are no strings in lowercase letters (except for `NoneType`).
Therefore, by changing the line:
```
parser.add_argument(
"--schema",
type=str,
...
```
to:
```
parser.add_argument(
"--schema",
type=str.upper,
...
```
Automate the conversion of the `--schema` parameter input by the user. Especially since the general habit is to type in lowercase.
Although this is a very simple thing, it is better to automate it.

Add `.upper` method for `--schema` parameter

---

seacrowd/sea_datasets/asr_indocsc/asr_indocsc.py

Closes #438 | Add dataloader for ASR-INDOCSC

---

requirements.txt
seacrowd/sea_datasets/lio_and_central_flores/lio_and_central_flores.py
seacrowd/sea_datasets/lio_and_central_flores/path_url.py
seacrowd/sea_datasets/lio_and_central_flores/processing.py

Closes #312 | Create lio_and_central_flores dataset loader

---

seacrowd/sea_datasets/parallel_asian_treebank/parallel_asian_treebank.py

Closes #109 | Add Dataloader Asian Parallel Treebank Corpus

---

seacrowd/sea_datasets/malaysia_ai_government/malaysia_ai_government.py

**Title**: Closes #421 | Add/Update Dataloader malaysia_ai_government
**First line PR Message**: Closes #421
- [-] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

Closes #421 | Add/Update Dataloader malaysia_ai_government

---

seacrowd/sea_datasets/malaysia_ai_hansard/malaysia_ai_hansard.py

**Title**: Closes #423 | Add/Update Dataloader malaysia_ai_hansard
**First line PR Message**: 
Closes #423
- [-] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

Closes #423 | Add/Update Dataloader malaysia_ai_hansard

---

seacrowd/sea_datasets/thai_ser/thai_ser.py

Closes #102 | Add Dataloader for Thai SER

---

seacrowd/sea_datasets/asr_malcsc/asr_malcsc.py

Closes #442 | Add dataloader for ASR-MALCSC

---

seacrowd/sea_datasets/okapi_m_arc/okapi_m_arc.py

Closes #474
Test Indonesian subset: `./test_example.sh okapi_m_arc --subset_id okapi_m_arc_ind`
Test Vietnamese subset:  `./test_example.sh okapi_m_arc --subset_id okapi_m_arc_vie`

Closes #474 | Add Dataloader OKAPI mARC

---

seacrowd/sea_datasets/total_defense_meme/total_defense_meme.py
seacrowd/utils/constants.py
seacrowd/utils/schemas/__init__.py
seacrowd/utils/schemas/image.py

Closes #355
There are 2 tasks with different schemas. The OCR task is intended for all the images, but the ImageClassification task is only for those having `pillar_stances` attribute since the dataset is about pillar classification, CMIIW.
Also, the new `image` schema is added here instead of in a new PR for example sake. Once checked and okay, I will add a new PR for adding the new schema, and remove the relevant files from this PR.
Also again, similar to #556 and #566: I use third-party libraries to download the GDrive data, i.e., `pip install gdown`, because it is more reliable than the `dl_manager`. Similarly, I also store the downloaded data in `data/total_defense_meme/`. I am aware that I should make or wait for a PR on those two things, so currently waiting for further …

Closes #355 | Add Dataloader TotalDefMeme 

---

seacrowd/sea_datasets/squad_id_nli/squad_id_nli.py

**Title**: Add Dataloader SQuAD-ID-NLI
**First line PR Message**: Closes https://github.com/SEACrowd/seacrowd-datahub/issues/617
- For the `_CITATION` field, because of the notification of my workshop on 18 April, I still can't write that section. On 18 April, I will revisit and change this `_CITATION`.

Closes #617 | Add Dataloader SQuAD-ID-NLI

---

seacrowd/sea_datasets/okapi_m_mmlu/okapi_m_mmlu.py

Closes #476
Test Indonesian subset: ./test_example.sh okapi_m_mmlu --subset_id okapi_m_mmlu_ind
Test Vietnamese subset: ./test_example.sh okapi_m_mmlu --subset_id okapi_m_mmlu_vie

Closes #476 | Add/Update Dataloader OKAPI m-MMLU

---

seacrowd/sea_datasets/minang_senti/minang_senti.py

Closes #574
I implemented one config per language/subset. Thus, configs will look like this: `minang_senti_min_source`, `minang_senti_ind_seacrowd_text`, etc. When testing, pass `minang_senti_<subset>` to the `--subset_id` parameter.

Closes #574 | Add Dataloader MinangNLP Sentiment Analysis

---

seacrowd/sea_datasets/brcc/brcc.py

Closes #519 | Add dataloader for BRCC

---

seacrowd/sea_datasets/alice_thi/alice_thi.py

Closes #225 
I implemented one config per language/subset. Thus, configs will look like this: `alice_thi_THI-C68_source`, `alice_thi_THI-D10_seacrowd_imtext`, etc. When testing, pass `alice_thi_<subset>` to the `--subset_id` parameter.

Closes #225 | Add Dataloader ALICE-THI

---

seacrowd/sea_datasets/multilingual_nli_26lang/multilingual_nli_26lang.py

Closes #583 
There are 10 subsets. Configs will look like this: `multilingual_nli_26lang_id_anli_source`, `multilingual_nli_26lang_vi_ling_seacrowd_pairs`, etc. When testing, pass `multilingual_nli_26lang_<subset>` to the `--subset_id` parameter.
<details close>
<summary>Here is a useful script to test all subsets:</summary>
To run this script, save it to a file (e.g., `mnli_tests.sh`), make it executable with `chmod +x mnli_tests.sh`, and execute it with `./mnli_tests.sh`. Ensure you run the script from the seacrowd root directory.
```bash
#!/bin/bash
DATASET="multilingual_nli_26lang"
LANGS=("id" "vi")
SUBSETS=("anli" "fever" "ling" "mnli" "wanli")
mkdir -p data/${DATASET}
success_count=0
fail_count=0
declare -a failed_tests
for lang in "${LANGS[@]}"; do
for subset in "${SUBSETS[@]}"; do …
```

Closes #583 | Add Dataloader multilingual-NLI-26lang-2mil7

---

seacrowd/sea_datasets/thai_tnhc2_books/thai_tnhc2_books.py

Closes #619 | Add/Update Dataloader thai-tnhc2-books

---

seacrowd/sea_datasets/bm_pt3/bm_pt3.py

Closes #529 | Add/Update Dataloader BM-PT3

---

seacrowd/sea_datasets/mdia/mdia.py

Closes #527
I implemented one config per language/subset. Thus, configs will look like this: `mdia_ind_dialogue_source`, `mdia_tgl_eng_seacrowd_t2t`, etc. When testing, pass `mdia_<subset>` to the `--subset_id` parameter.
Note: this dataset can be used for two tasks and both use the same `t2t` schema with different implementation.

Closes #527 | Add Dataloader MDIA

---

seacrowd/sea_datasets/multilingual_alpaca/multilingual_alpaca.py

Closes #531
Similar to #556: I use third-party libraries to download the GDrive data, i.e., `pip install gdown`, because it is more reliable than the `dl_manager`. Similarly, I also store the downloaded data in `data/multilingual_alpaca/`. I am aware that I should make a PR for those two things, just waiting for further instructions.

Closes #531 | Add Dataloader Multilingual-ALPACA

---

seacrowd/sea_datasets/multispider/multispider.py

**Title**: Add Dataloader Multsipider
**First line PR Message**: Closes https://github.com/SEACrowd/seacrowd-datahub/issues/610

Closes #610 | Add Dataloader Multsipider

---

seacrowd/sea_datasets/culturay/culturay.py

Closes #535 
I implemented one config per language/subset. Thus, configs will look like this: `culturay_id_source`, `culturay_my_seacrowd_ssp`, etc. When testing, pass `culturay_<subset>` to the `--subset_id` parameter.
Due to the large dataset, it will take time to test.

Closes #535 | Add Dataloader CulturaY

---

seacrowd/sea_datasets/idk_mrc_nli/idk_mrc_nli.py

**Title**: Add Dataloader IDK-MRC-NLI
**First line PR Message**: Closes https://github.com/SEACrowd/seacrowd-datahub/issues/615
- For the `_CITATION` field, I will add it later.

Closes #615 | Add Dataloader IDK-MRC-NLI

---

seacrowd/sea_datasets/hplt/hplt.py

Closes #524
I implemented one config per language+subset. Thus, configs will look like this: `hplt_id_raw_source`, `hplt_my_cleaned_seacrowd_ssp`, etc. When testing, pass `hplt_<subset>` to the `--subset_id` parameter.
Due to the huge size, it may take some time to download the data. For efficient testing, I suggest testing by copying some part of this code and using either of these subsets: `my_cleaned` (smallest seacrowd subset), `cy_cleaned` (smallest one-file-dataset), or `sk_cleaned` (smallest two-files-dataset) if you're interested.
Just a heads-up, I noticed `vie` language is included in the dataset's [supported languages](https://huggingface.co/datasets/HPLT/hplt_monolingual_v1_2#supported-languages) but not listed in datasheet #524. I haven't checked for other possible unlisted …

Closes #524 | Add Dataloader HPLT

---

seacrowd/sea_datasets/tydiqa_id_nli/tydiqa_id_nli.py

**Title**: Add Dataloader TyDIQA-ID-NLI
**First line PR Message**: Closes https://github.com/SEACrowd/seacrowd-datahub/issues/616
- For the `_CITATION` field, I will add it later.

Closes #616 | Add Dataloader TyDIQA-ID-NLI

---

seacrowd/sea_datasets/lex_indo/lex_indo.py

Closes #437 | Create lex_indo dataset loader

---

seacrowd/sea_datasets/vicon/vicon.py

**Title**: Add Dataloader ViCon
**First line PR Message**: Closes https://github.com/SEACrowd/seacrowd-datahub/issues/578

Closes #578 | Add Dataloader ViCon

---

seacrowd/sea_datasets/duolingo_staple_2020/duolingo_staple_2020.py

Closes #522 
I implemented one config per language/subset. Thus, configs will look like this: `duolingo_staple_2020_aws_baseline_source`, `duolingo_staple_2020_gold_seacrowd_t2t`, etc. When testing, pass `duolingo_staple_2020_<subset>` to the `--subset_id` parameter.
Also, this one is a local dataset since you need to fill a form to download them [here](https://doi.org/10.7910/DVN/38OJR6) (no static URL provided). So don't forget to pass where you store `staple-2020` data to `data_dir` parameter.
Here are the test results:
[duolingo_staple_2020_aws_baseline.txt](https://github.com/SEACrowd/seacrowd-datahub/files/14815203/duolingo_staple_2020_aws_baseline.txt)
[duolingo_staple_2020_gold.txt](https://github.com/SEACrowd/seacrowd-datahub/files/14815202/duolingo_staple_2020_gold.txt)

Closes #522 | Add Dataloader Duolingo STAPLE 2020

---

seacrowd/sea_datasets/vilexnorm/vilexnorm.py

Closes #584 | Add/Update Dataloader ViLexNorm

---

seacrowd/sea_datasets/medisco/medisco.py

Closes #591 | Add/Update medisco

---

seacrowd/sea_datasets/aya_evaluation_suite/aya_evaluation_suite.py

**Title**: Add Dataloader Aya Evaluation Suite
**First line PR Message**: Closes https://github.com/SEACrowd/seacrowd-datahub/issues/479
Test:
You can check this dataloader implementation by copy-pasting this command (to make a faster evaluation):
```
python -m tests.test_seacrowd seacrowd/sea_datasets/aya_evaluation_suite/aya_evaluation_suite.py --subset_id aya_evaluation_suite_ceb
python -m tests.test_seacrowd seacrowd/sea_datasets/aya_evaluation_suite/aya_evaluation_suite.py --subset_id aya_evaluation_suite_tha
python -m tests.test_seacrowd seacrowd/sea_datasets/aya_evaluation_suite/aya_evaluation_suite.py --subset_id aya_evaluation_suite_mya
python -m tests.test_seacrowd seacrowd/sea_datasets/aya_evaluation_suite/aya_evaluation_suite.py --subset_id aya_evaluation_suite_zsm
python -m …
```

Closes #479 | Add Dataloader Aya Evaluation Suite

---

seacrowd/sea_datasets/vsolscsum/vsolscsum.py

**Title**: Add Dataloader VSoLSCSum
**First line PR Message**: Closes https://github.com/SEACrowd/seacrowd-datahub/issues/580

Closes #580 | Add Dataloader VSoLSCSum

---

seacrowd/sea_datasets/xed/xed.py

**Title**: Add Dataloader XED
**First line PR Message**: Closes https://github.com/SEACrowd/seacrowd-datahub/issues/533
Note: 
- I changed the `_LICENSE` by `Licenses.CC_BY_4_0.value` despite of license information on the dataloader issue here https://github.com/SEACrowd/seacrowd-datahub/issues/533 is `Licenses.UNKNOWN.value`. I'd rather take license information from the bottom of [homepage's](https://github.com/Helsinki-NLP/XED) `README.md`.
- I also changed the `_SUPPORTED_TASKS` to `Tasks.ASPECT_BASED_SENTIMENT_ANALYSIS` instead of `Tasks.SENTIMENT_ANALYSIS` due to the fact that this dataset is multi-label, so I will need `text_multi` as schema not `text`.
- From the homepage, I found that Indonesian is already there (it's already told on this comment: …

Closes #533 | Add Dataloader XED

---

seacrowd/sea_datasets/lexitron/lexitron.py
seacrowd/utils/configs.py

**Title**: Add Dataloader LEXiTRON
**First line PR Message**: Closes https://github.com/SEACrowd/seacrowd-datahub/issues/614
**Note**: There are no citations available for this dataset.

Closes #614 | Add Dataloader LEXiTRON

---

seacrowd/sea_datasets/aya_collection_translated/aya_collection_translated.py

**Title**: Add Dataloader Aya Collection - Translated
**First line PR Message**: Closes https://github.com/SEACrowd/seacrowd-datahub/issues/480
Test:
You can check this dataloader implementation by copy-pasting this command (to make a faster evaluation). Note that, the evaluation will take a long time due to the huge size of the dataset (since some of the dataset size is >2 GB):
```
python -m tests.test_seacrowd seacrowd/sea_datasets/aya_collection_translated/aya_collection_translated.py --subset_id aya_collection_translated_ceb
python -m tests.test_seacrowd seacrowd/sea_datasets/aya_collection_translated/aya_collection_translated.py --subset_id aya_collection_translated_tha
python -m tests.test_seacrowd seacrowd/sea_datasets/aya_collection_translated/aya_collection_translated.py …
```

Closes #480 | Add Dataloader Aya Collection - Translated

---

seacrowd/sea_datasets/gowajee/gowajee.py

Closes #586 | Add Dataloader Gowajee Corpus

---

seacrowd/sea_datasets/wikihow_gosc/wikihow_gosc.py

Closes #526.
Notes:
- `gdown` is used to download from GDrive, see #556 and #566 for similar implementations.
- Only `source` schema is implemented is done after discussing with Holy.

Closes #526 | Add dataloader for WIkiHow-GOSC

---

seacrowd/sea_datasets/bud500/bud500.py

Closes #537
This dataset is MASSIVE, and it seems the seacrowd test must download ALL data for it to be _OK_. I downloaded and loaded all the files (~100gb) and successfully tested it. I'm putting the result here: [bud500.txt](https://github.com/SEACrowd/seacrowd-datahub/files/14817853/bud500.txt)
For those with limited internet quota, I'm suggesting to load the data in Python's REPL, passing `streaming=True` as follows:
```python
>>> from datasets import load_dataset
>>> 
>>> data = load_dataset("seacrowd/sea_datasets/bud500", name="bud500_source", split="train", streaming=True)
>>> list(data.take(3))
[{'audio': {'path': None, 'array': array([ 0.04827881, ..., -0.08636475]), 'sampling_rate': 16000}, 'transcription': 'thế mà hôm nay lại nghe em gái nhắc đến'},
{'audio': {'path': None, …
```

Closes #537 | Add Dataloader Bud500

---

seacrowd/sea_datasets/vimmrc/vimmrc.py

Closes #577 | Add Dataloader ViMMRC

---

seacrowd/sea_datasets/msl4emergency/msl4emergency.py

Closes #569  | Add/Update Dataloader MSL4Emergency

---

seacrowd/sea_datasets/clir_matrix/clir_matrix.py
tests/test_seacrowd.py

Closes #426
**_source-only_** dataloader.
---
Note:
- As this dataloader is source-only, seacrowd schema is not implemented.
- test was done using `tests.test_seacrowd_source_only.py`.

Closes #426 | Create dataset loader for CLIRMatrix

---

seacrowd/sea_datasets/uit_viwikiqa/uit_viwikiqa.py

Closes #625
Test result screenshot (local data):

Closes #625 | Add Dataloader UIT-ViWikiQA

---

seacrowd/sea_datasets/vlogqa/vlogqa.py

Closes #621
Local dataset test result screenshot:
<details close>
<summary>Full test result:</summary>
```
(seacrowd) ➜  seacrowd-datahub git:(vlogqa) ✗ python -m tests.test_seacrowd seacrowd/sea_datasets/vlogqa/vlogqa.py --data_dir=data/vlogqa
INFO:__main__:args: Namespace(path='seacrowd/sea_datasets/vlogqa/vlogqa.py', schema=None, subset_id=None, data_dir='data/vlogqa', use_auth_token=None)
INFO:__main__:self.PATH: seacrowd/sea_datasets/vlogqa/vlogqa.py
INFO:__main__:self.SUBSET_ID: vlogqa
INFO:__main__:self.SCHEMA: None
INFO:__main__:self.DATA_DIR: data/vlogqa
INFO:__main__:Checking for _SUPPORTED_TASKS ...
module seacrowd.sea_datasets.vlogqa.vlogqa
INFO:__main__:Found _SUPPORTED_TASKS=[<Tasks.QUESTION_ANSWERING: 'QA'>]
INFO:__main__:_SUPPORTED_TASKS implies _MAPPED_SCHEMAS={'QA'} …
```

Closes #621 | Add Dataloader VlogQA

---

seacrowd/sea_datasets/up2/up2.py
seacrowd/utils/common_parser.py

Closes #571 
---
Currently implemented as source-only, as there seems to be no matching task.
(Based on the information provided in the card)
Issue was initially raised in the [issue thread #571](https://github.com/SEACrowd/seacrowd-datahub/issues/571#issuecomment-2073953395).

Closes #571 | Add/Update Dataloader UP2.0

---

seacrowd/sea_datasets/mywsl2023/mywsl2023.py

Closes [#278](https://github.com/SEACrowd/seacrowd-datahub/issues/278)

Closes #278 | Add mywsl2023 dataloader

---

seacrowd/sea_datasets/medev/medev.py

Closes #623 | Add/Update Dataloader MedEV

---

seacrowd/sea_datasets/thai_elderly_speech/thai_elderly_speech.py

Closes #590 
I implemented one config per subset. Thus, configs will look like this: `thai_elderly_speech_healthcare_source`, `thai_elderly_speech_smarthome_seacrowd_sptext`, etc. When testing, pass `thai_elderly_speech_<subset>` to the `--subset_id` parameter.

Closes #590 | Add Dataloader Thai Elderly Speech

---

seacrowd/sea_datasets/vlsp2020_mt_envi/vlsp2020_mt_envi.py

Closes #629 
**NB**
- Skipping `openSub` & `mono-vi` for future development (Large Drive file download bottleneck), already opened thread in Discord discussion.
- Tested 3 out of 7 subsets

Closes #629 | Add/Update Dataloader VLSP2020 MT

---

seacrowd/sea_datasets/m3ls/m3ls.py

Closes #228 | Add M3LS dataloader

---

seacrowd/sea_datasets/vimqa/vimqa.py

Closes #576
Here is the output of the unit-tests:
```
INFO:__main__:args: Namespace(path='seacrowd/sea_datasets/vimqa/vimqa.py', schema=None, subset_id=None, data_dir='seacrowd/sea_datasets/vimqa/data', use_auth_token=None)
INFO:__main__:self.PATH: seacrowd/sea_datasets/vimqa/vimqa.py
INFO:__main__:self.SUBSET_ID: vimqa
INFO:__main__:self.SCHEMA: None
INFO:__main__:self.DATA_DIR: seacrowd/sea_datasets/vimqa/data
INFO:__main__:Checking for _SUPPORTED_TASKS ...
module seacrowd.sea_datasets.vimqa.vimqa
INFO:__main__:Found _SUPPORTED_TASKS=[<Tasks.QUESTION_ANSWERING: 'QA'>]
INFO:__main__:_SUPPORTED_TASKS implies _MAPPED_SCHEMAS={'QA'}
INFO:__main__:schemas_to_check: {'QA'}
INFO:__main__:Checking load_dataset with config name vimqa_source …
```

Closes #576 | Add Dataloader `Vimqa`

---

seacrowd/sea_datasets/sentiment_taglish_product_review/sentiment_taglish_product_review.py

Closes #720 | Add Sentiment-Annotated Taglish Product and Service Reviews dataloader

---

seacrowd/sea_datasets/nusatranslation_mt/nusatranslation_mt.py

I wanna report that there are bugs in the that NusaTranslationMT dataloader on [SEACrowd HF](https://github.com/SEACrowd/seacrowd-datahub/blob/master/seacrowd/sea_datasets/nusatranslation_mt/nusatranslation_mt.py).
1. There is `abs` language on the `LANGUAGES_MAP` and the URL is exists (https://raw.githubusercontent.com/IndoNLP/nusa-writes/main/data/nusa_kalimat-mt-abs-train.csv), but doesn't exist on `_LANGUAGES` variable, so it cannot be reached.
2. The case is same like (1) for `bhp` language.
3. Now, the case is a little inverted here. There is no `bug` language on `LANGUGES_MAP` and the URL isn't exists, but it exist on `_LANGUAGES` variable, so it caused error `FileNotFound`.
Furthermore, I added `assert` statement to ensure the `LANGUGES_MAP` is a correct subset of `_LANGUAGES`. I …

Fix `abs`, `bhp` and `bug` languages issue on `SEACrowd/nusatranslation_mt`

---

seacrowd/sea_datasets/flores200/flores200.py

Refactor FLORES-200 script change source schema & update script for loading the new FLORES-200 v2.0 from `openlanguagedata/flores_plus`
**Title**: Update FLORES-200  
Note: the `source` and `seacrowd_t2t` have completely different schema now, where the `source `only has the sentence for a certain language (as how it is implemented in `openlanguagedata/flores_plus`) and the `seacrowd_t2t` is implemented for the actual MT task.

Refactor FLORES-200 script
